INSERT INTO
    application (
        application_id,
        full_name,
        phone_number,
        email,
        dob,
        gender,
        student_id,
        university,
        faculty,
        major,
        class,
        cv_type,
        cv_link,
        apply_date,
        round,
        application_status,
        department_name,
        note
    )
VALUES (
        gen_random_uuid (),
        'Nguyễn Văn A',
        '0123456789',
        'vana@st.ueh.edu.vn',
        '2000-01-01',
        'Nam',
        '3123000001',
        'Đại học Kinh tế TP.HCM',
        'CNTT',
        'CNTT',
        'ET0001',
        'CV mẫu',
        'https://cvlink.com/1',
        CURRENT_TIMESTAMP,
        1,
        'Pending',
        'Ban Chuyên môn',
        'Ghi chú 1'
    ),
    (
        gen_random_uuid (),
        'Trần Thị B',
        '0987654321',
        'thib@st.ueh.edu.vn',
        '2001-02-02',
        'Nữ',
        '3123000002',
        'Đại học Kinh tế TP.HCM',
        'CNTT',
        'CNTT',
        'ET0002',
        'CV tự thiết kế',
        'https://cvlink.com/2',
        CURRENT_TIMESTAMP,
        2,
        'Approved',
        'Ban Truyền thông',
        'Ghi chú 2'
    ),
    (
        gen_random_uuid (),
        'Lê Văn C',
        '0911222333',
        'levanc@st.ueh.edu.vn',
        '2002-03-03',
        'Nam',
        '3123000003',
        'Đại học Kinh tế TP.HCM',
        'CNTT',
        'CNTT',
        'ET0003',
        'CV mẫu',
        'https://cvlink.com/3',
        CURRENT_TIMESTAMP,
        3,
        'Rejected',
        'Ban Nhân sự - Tổ chức',
        'Ghi chú 3'
    ),
    (
        gen_random_uuid (),
        'Phạm Thị D',
        '0933444555',
        'phamthid@st.ueh.edu.vn',
        '2003-04-04',
        'Nữ',
        '3123000004',
        'Đại học Kinh tế TP.HCM',
        'CNTT',
        'CNTT',
        'ET0004',
        'CV tự thiết kế',
        'https://cvlink.com/4',
        CURRENT_TIMESTAMP,
        1,
        'Pending',
        'Ban Sự kiện',
        'Ghi chú 4'
    ),
    (
        gen_random_uuid (),
        'Võ Văn E',
        '0944555666',
        'vovane@st.ueh.edu.vn',
        '2004-05-05',
        'Nam',
        '3123000005',
        'Đại học Kinh tế TP.HCM',
        'CNTT',
        'CNTT',
        'ET0005',
        'CV mẫu',
        'https://cvlink.com/5',
        CURRENT_TIMESTAMP,
        2,
        'Approved',
        'Ban Tài chính - Đối ngoại',
        'Ghi chú 5'
    );