openapi: 3.0.4
info:
  title: ET-Web API Documentation
  version: 1.0.0
  description: |-
    This is the API documentation for ET-Web application. The API provides endpoints for managing:
    - Achievements
    - Activities
    - News & Blogs
    - Partners
    - Personnel & Accounts
    - System Roles
    - FAQs
    - Banners
    - Terms

    For any questions or issues, please contact the development team.
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://api.etclub.click
    description: Production server
tags:
  - name: achievements
    description: Operations about achievements
  - name: activities
    description: Operations about activities
  - name: et-news
    description: Operations about ET news
  - name: et-blog
    description: Operations about ET blog
  - name: partners
    description: Operations about partners
  - name: personnels
    description: Operations about personnel management
  - name: accounts
    description: Operations about user accounts
  - name: system-role
    description: Operations about system roles
  - name: banners
    description: Operations about banners
  - name: faqs
    description: Operations about FAQs
  - name: terms
    description: Operations about terms
  - name: auth
    description: Operations about authentication
  - name: search
    description: Operations about search functionality
paths: {}
components:
  schemas:
    SuccessResponse: #status 200
      type: object
      properties:
        message:
          type: string
          example: Success
        data:
          type: object
          nullable: true
          example:
            id: "123"
            title: "Morning Run"
            createdAt: "2025-08-01T10:20:30Z"

    CreatedResponse: #status 201
      type: object
      properties:
        message:
          type: string
          example: Resource created successfully
        data:
          type: object
          example:
            id: "123"
            title: "Morning Run"

    ErrorResponse: #status 400, 401, 404, 500
      type: object
      properties:
        message:
          type: string
          example: The 'email' field must be a valid email address

  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
